version: "3"

services:
  web:
    build:
      context: .
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"

  rabbitmq3:
    container_name: "rabbitmq-server"
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'

  celery:
    build: .
    command: celery -A VastuBhandar worker -l info
    environment:
      CELERY_BROKER_URL: 'amqp://guest:guest@rabbitmq3:5672//'
    depends_on:
      - web
      - rabbitmq3


#  stripe_cli:
#    image: stripe/stripe-cli:latest
#    container_name: stripe_cli
#    environment:
#      STRIPE_SECRET_KEY: "sk_test_51JtQGMSEnLzHRlrPClGLHovBHUGyWlnyjZN2wR4B1FjYvYkCRDvsxrYudFYvw15nb2z4bXdV91AdUIZd7w8LYQvc00iSGUddMi"
#    command: stripe listen --forward-to localhost:8000/payments/my_webhook_view/
#    depends_on:
#      - web
