# Generated by Django 3.2.8 on 2021-11-17 06:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0012_auto_20211117_0621'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartBaseModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_of_add', models.DateTimeField(default=datetime.datetime(2021, 11, 17, 6, 21, 54, 204001, tzinfo=utc))),
                ('product_id', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('cartbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WishlistCart.cartbasemodel')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart_price', models.PositiveIntegerField(default=0)),
            ],
            bases=('WishlistCart.cartbasemodel',),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('cartbasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='WishlistCart.cartbasemodel')),
            ],
            bases=('WishlistCart.cartbasemodel',),
        ),
    ]
