# Generated by Django 3.2.8 on 2021-11-17 06:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WishlistCart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartbasemodel',
            name='date_of_add',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 6, 27, 58, 785641, tzinfo=utc)),
        ),
    ]
