# Generated by Django 3.2.8 on 2021-11-04 09:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('51c93b4b-e44b-42fb-af6d-cc98b77edf2c'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('details', models.TextField()),
                ('price', models.FloatField()),
                ('stocks', models.IntegerField()),
                ('availability', models.CharField(choices=[('Coming soon', 'Coming soon'), ('Available', 'Available'), ('Not Available', 'Not Available')], default='available', max_length=20)),
                ('category', models.CharField(choices=[('general', 'general'), ('fashion', 'fashion'), ('mobile', 'mobile'), ('books', 'books')], default='general', max_length=50)),
                ('image1', models.FileField(help_text='Add products image here', upload_to='product/images')),
                ('image2', models.FileField(help_text='Add products image here', upload_to='product/images')),
                ('image3', models.FileField(help_text='Add products image here', upload_to='product/images')),
                ('image4', models.FileField(blank=True, help_text='Add products image here', upload_to='product/images')),
                ('image5', models.FileField(blank=True, help_text='Add products image here', upload_to='product/images')),
                ('Video', models.FileField(help_text='Add products video here', upload_to='product/videos')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 11, 4, 9, 19, 28, 808665, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2021, 11, 4, 9, 19, 28, 808678, tzinfo=utc))),
            ],
        ),
    ]
