# Generated by Django 3.2.8 on 2021-11-08 09:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('wishlistcart', '0001_initial.py'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCheckOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('payment_id', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('successful', 'successful'), ('failed', 'failed'), ('in_process', 'in_process'), ('initiate', 'initiate')], default='initiate', max_length=500)),
                ('created_at', models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 8, 9, 16, 9, 659681, tzinfo=utc))),
                ('updated_at', models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 8, 9, 16, 9, 659692, tzinfo=utc))),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishlistCart.usercart')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchased_on', models.DateTimeField(verbose_name=datetime.datetime(2021, 11, 8, 9, 16, 9, 659902, tzinfo=utc))),
                ('Payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentcheckout')),
            ],
        ),
    ]
