# Generated by Django 3.2.8 on 2021-11-17 06:29

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WishlistCart', '0003_alter_cartbasemodel_date_of_add'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='purchased_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 6, 29, 20, 916338, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='paymentcheckout',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WishlistCart.usercart', unique=True),
        ),
        migrations.AlterField(
            model_name='paymentcheckout',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 6, 29, 20, 916064, tzinfo=utc), editable=False),
        ),
        migrations.AlterField(
            model_name='paymentcheckout',
            name='status',
            field=models.CharField(choices=[('unpaid', 'unpaid'), ('paid', 'paid'), ('in_process', 'in_process'), ('initiate', 'initiate')], default='initiate', max_length=500),
        ),
        migrations.AlterField(
            model_name='paymentcheckout',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 17, 6, 29, 20, 916080, tzinfo=utc)),
        ),
    ]
