# Generated by Django 3.2.8 on 2021-11-03 10:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211102_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 10, 38, 41, 39283, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 10, 38, 41, 39301, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 10, 38, 41, 37625, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 3, 10, 38, 41, 37644, tzinfo=utc)),
        ),
    ]
